apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: request-logger
  namespace: my-namespace
spec:
  template:
    metadata:
      annotations:
        # Target 10 in-flight-requests per pod.
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
        - image: docker.io/aliok/request-logger
          env:
            - name: LATENCY
              value: "100"
